### ISSUE TITLE
Question about SNP-gene correlation matrix

### ISSUE THREAD

**Issue by Xinyu-Sun** [simingz/ctwas#15]
Thanks for developing this useful tools! In ctwas_process_regions.R at line 270, the code include R_snp[x,x] in the denominator. This term is not present in the equation from the paper's Supplementary Notes. Could you explain what is this term used for?
```
            R_snp_gene[,i] <- sapply(1:nrow(R_snp),
                                     function(x){crossprod(wgt,R_snp[ld.idx,x])/sqrt(crossprod(wgt,R.s)%*%wgt*R_snp[x,x])})
```
,Xinyu

**Comment by simingz** [comment]
Hi Xinyu, thanks for using our software. In the supplement, we assume R is the correlation matrix, so R_snp[x,x]= 1. That's why this term didn't show up in the equation. I think at the time when we implemented this part, we didn't require that (can be covariance or correlation matrix). As now we are requiring R should be the correlation matrix (LD matrix), this term shouldn't matter.

**Comment by Xinyu-Sun** [comment]
Got it. Thank you!
